[package]
name = "tester"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 2
lto = true
debug = 2
codegen-units = 1

[profile.release]
opt-level = "s"
lto = true
debug = 2

[dependencies]
mos-hardware = "0"
ufmt-stdio = "0"

